[Ideas]
Vim setup
How the modern web is bloated
Philosophy - Should the gov put rules in social media
Wal theme for spotify
Nyc photoshoot
NVIDIA DOESN'T WORK ONLY WHILE USING LIGHTDM

[Doing]
Chip 8 emulator in rust


[Done]
Custom keyboard
Desktop Setup
how this site was made

[Bad-Idea]

