[Ideas]
- Why you shouldn't go to class your first semester
    - Use atomic essay format
        - as short as possible, while still conveying ideas

[Doing]
Chip 8 emulator in rust


[Done]
Custom keyboard
Desktop Setup
how this site was made

[Bad-Idea]

